#!/bin/bash

# Mendapatkan informasi volume dan status mute menggunakan amixer
volume_info=$(amixer get Master | grep -oE "[0-9]+%|\[on\]|\[off\]")

# Mengambil nilai volume dan status mute dari output
volume=$(echo "$volume_info" | awk 'NR==1{print $1}' | tr -d '%')
mute_status=$(echo "$volume_info" | awk 'NR==2{print $1}')

# Menampilkan ikon sesuai dengan status mute
if [ "$mute_status" == "[off]" ]; then
  echo "󰝟"
else
  echo " $volume%"
fi

